### ISSUE TITLE
Single Sign Out for Sinatra

### ISSUE THREAD

**Issue by jordanthornquest** [biola/rack-cas#17]
What needs to be done to get this working? I'd love to contribute.

**Comment by adamcrown** [comment]
Sorry it's been so long and I haven't had time to look into this. Are you still looking for a solution for this or should I close the issue?

**Comment by jordanthornquest** [comment]
Hello, Adam! I realized I missed your comment. I no longer need a solution :)

**Comment by rvalenciano** [comment]
Any solution for this @adamcrown ?

**Comment by adamcrown** [comment]
@rvalenciano Sorry it took me a while to get back to you. Are you still having this problem?
