### ISSUE TITLE
Build a controller to serve fake login form

### ISSUE THREAD

**Issue by nicolasiensen** [biola/rack-cas#24]
In a [previous conversation](https://github.com/biola/rack-cas/commit/c0abaee59b91d504390307cb0474023cdcdf62f2#diff-6c7c4ef61892be7d13c99ff8fedaea01R36), I was telling @adamcrown to implement a route, available when rack-cas is on the test mode, to access the login form provided by the FakeCAS.

Today this login form is only accessible when the controller returns a 401 unauthorized response, and I wish to have a route like ```/fake_cas_login``` which calls a FakeCAS controller to serve this login form.

Generally, when I use rack-cas, the rescue strategy for unauthorized access is to [redirect the user to the CAS server's login page](https://github.com/meurio/compartilhaco/blob/master/app/controllers/application_controller.rb#L11).

This is what should happen in production, but for the development and test environments we don't expect that, since the CAS server serves only the production environment.

**Comment by adamcrown** [comment]
This has been pushed to master. I'll be releasing 0.10.0 soon which will have this functionality.

**Comment by nicolasiensen** [comment]
Awesome! Thanks @adamcrown!!
