### ISSUE TITLE
Integration with CASino

### ISSUE THREAD

**Issue by pedrohenriquerls** [biola/rack-cas#34]
I'm trying to use the RackCAS on my client , with casino as my server cas.
I followed the instructions in the readme, but I can not get the session my client and also do not see any attempt to access api my cas server, is there any example using is gem with rails?

**Comment by adamcrown** [comment]
I don't have an basic example Rails application. I could create one but I doubt I'll have time to work on that soon. You can look at [one of our open source applications](https://github.com/biola) such as (three-keepers)[https://github.com/biola/three-keepers]. It's probably more complex than you need, but it is a working example.

We use rubycas-server but I'd like to switch to CASino. If you run into any problems specifically with CASino, I'd like to know.

**Comment by pedrohenriquerls** [comment]
I saw his three-keepers project and adopted quite a lot of his organization, but now I 'm try this warning " ActionDispatch :: Session :: RackCasMongoidStore failed to save session. Content dropped. " I could not understand why this happens, you can you tell me what causes this?

**Comment by adamcrown** [comment]
Sorry it's been so very long in getting back to you about this. I've recently moved overseas and am working on freelance projects now. But I have some time to work on rack-cas now since I'm between projects.

Did you ever get this resolved?

**Comment by pedrohenriquerls** [comment]
No problem dude, yeah i solved my issue with a [rack-cas-client](https://github.com/pedrohenriquerls/rack-cas-client/tree/feature) gem, him is more simple. 
Your gem is overkill to my problem.
Ty a lot for all help and tips ;)
