### ISSUE TITLE
session pruning in production

### ISSUE THREAD

**Issue by dsusco** [biola/rack-cas#38]
Not so much an issue, as a documentation request. I'm confused with what rack_cas:sessions:prune:active_record is doing? Is it just removing sessions from the table that were never logged out?

What's a good approach to running this in production? Just a cron job? Something else?

**Comment by mikestephens** [comment]
Hey there!

Sorry for the delayed response to this, but I figured I'd answer it in case anyone else has this issue.

The active_record pruning removes all tickets over 30 days old, by which time they should be expired.

You can run it manually but I do not recommend that. We have it set as a cron job, or a delayed worker (resque or sidekiq if using ruby)
