### ISSUE TITLE
401 status not getting intercepted

### ISSUE THREAD

**Issue by nozpheratu** [biola/rack-cas#49]
According to the docs
> Your app should return a 401 status whenever a request is made that requires authentication. Rack-CAS will catch these responses and attempt to authenticate via your CAS server.

Using the following configuration on my development server: 
```ruby
{
  :server_url => "http://localhost:3001/",
  :session_store => RackCAS::ActiveRecordStore,
  :verify_ssl_cert => false,
  :renew => true
}
```

I have a [CASino](http://casino.rbcas.com/) server running on port 3001. Here's my log files when I hit a 401 status while trying to access an ActiveAdmin page require authorization: 
>
Started GET "/admin/referrals/new" for 127.0.0.1 at 2015-11-30 18:27:33 -0600
Processing by Admin::ReferralsController#new as HTML
Completed 401 Unauthorized in 2ms (ActiveRecord: 0.0ms)
>
Started GET "/admin/login" for 127.0.0.1 at 2015-11-30 18:27:33 -0600
Processing by ActiveAdmin::Devise::SessionsController#new as HTML
  Rendered /home/cyle/.rvm/gems/ruby-2.2.2/bundler/gems/activeadmin-5a2b7b5bc683/app/views/active_admin/devise/shared/_links.erb (0.3ms)
  Rendered /home/cyle/.rvm/gems/ruby-2.2.2/bundler/gems/activeadmin-5a2b7b5bc683/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (19.8ms)
Completed 200 OK in 41ms (Views: 37.9ms | ActiveRecord: 0.0ms)

I'm not really seeing anything to indicate that rack-cas is indeed intercepting the 401 response. I noticed ActiveAdmin wasn't setting the status correctly in the response header, so to discern if this was an ActiveAdmin issue I also tried to manually return a 401 status in one of my controller actions with the correct header and met similar results. Is there some way I can go about debugging this further?

**Comment by adamcrown** [comment]
I don't have much experience with ActiveAdmin. So there might be something there that's causing problems.

First step would be to run `rake middleware` and make sure Rack::CAS is in the list.

When you visit the page do you get a 200 or 401 status? If it's a 401 status then Rack::CAS isn't catching it. If it's a 200, either you're not returning a 401 or Rack::CAS is catching it and logging you in.

You can look at `session[:cas]` and see if there's anything there to tell if authentication is happening or not.

Another easy test would be to visit the site in a incognito window (so you're sure you're not already logged into CASino) and see if you get the login page or not.

**Comment by nozpheratu** [comment]
@adamcrown It's indeed a 401 status. `session[:cas]` is nil, and just to make sure I tried visiting the route in incognito mode. I see `Rack::CAS` when I list my middleware.

I'll see if I can reproduce in a blank application.

**Comment by nozpheratu** [comment]
@adamcrown It seems to somewhat work under a new rails application, must be something on my end.

**Comment by adamcrown** [comment]
@nozpheratu Please do let me know what the problem winds up being. It could be helpful to other people in the future. Especially if it's something to do with ActiveAdmin.

Thanks.
