### ISSUE TITLE
Add path to service URL

### ISSUE THREAD

**Issue by eturk** [biola/rack-cas#53]
I have an application that is running on http://foo.example.com/app. Is there an easy way to tell rack-cas that my service URL lives at http://foo.example.com/app/service, rather than http://foo.example.com/service?

Thanks!

**Comment by adamcrown** [comment]
Hmm, that's interesting. It should do that automatically. Biola hosts a lot of applications with a relative URL root that use rack-cas.

I don't suppose your app is open source? I'd be happy to take a look if it is. It's a Rails app I assume?

Feel free to send me any relevant code and I can take a look.

**Comment by eturk** [comment]
It's unfortunately not open-sourced. However I did fork rack-cas and made enough modifications to get it to work (at least with the service URLs). The fork is at [marist-sga/rack-cas](https://github.com/marist-sga/rack-cas), and here are the relevant changes:

- https://github.com/marist-sga/rack-cas/blob/master/lib/rack-cas/server.rb#L13
- https://github.com/marist-sga/rack-cas/blob/master/lib/rack-cas/cas_request.rb#L19-L21

I added a `sub_uri` configuration option, and I'm just manually adding it to the beginning of the path of the  `service_url`. I've only done this for the service URL (since that's the only thing I need, I don't need the SSO stuff). I also haven't modified/written any tests for them yet, unfortunately!

I'm not sure if this is the best solution here. Ideally, the full host of the application would be configured globally and then the URLs would be made with that instead of the request URL.

**Comment by dsusco** [comment]
Out of curiosity, what does your web server environment look like? You might need to change/append to a request header somewhere.

For instance, we have multiple apps being served on a machine locally on different ports via Passenger. NGINX servers as a proxy, getting requests by locations and forwarding them on to the various Passengers, like so:

	location /my-app/ {
		proxy_pass http://0.0.0.0:4000/my-app/;

		proxy_buffering off;
		proxy_http_version 1.1;
		
		proxy_set_header Host $host; # more robust than http_host
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Proto https;
	}

**Comment by eturk** [comment]
We have something similar to you. There's the main public-facing server running Apache, proxying requests to `/rollcall` to another internal server running Nginx/Puma. I've tried using `proxy_request` with Nginx, but Rack CAS still sets the service URL as at the root path, rather than the sub-URI.

**Comment by adamcrown** [comment]
I know on some Nginx/Puma setups I've done I've added a sub-uri wrapper in `config.ru` to get Rails and Rack to recognize the fact that the app is being served from a sub-uri.

``` ruby
map ENV['PUMA_RELATIVE_URL_ROOT'] || '/' do
  run MyRailsApp::Application
end
```

All rack-cas is doing to generate a service URL is `Rack::Request#url` so there's nothing fancy going on. If that's not working it could be a sign of some other underlying problems that just haven't popped up yet.

**Comment by dsusco** [comment]
The only other thing I can think of is we had to set the `passenger_base_uri` in each of our Passenger standalones' config files.

https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_base_uri

Side note: our standalone Passengers are using the Passenger + NGINX deployment method.

**Comment by adamcrown** [comment]
Any update on this?

**Comment by adamcrown** [comment]
Gonna close this issue due to inactivity
