### ISSUE TITLE
Broken link on ReadMe

### ISSUE THREAD

**Issue by jfvanderwalt** [biola/rack-cas#61]
The link pointing to http://jasig.github.io/ on the ReadMe is currently broken/missing(multiple different repos seem to be referencing this domain).

More than happy to fix these if the domain has just moved/changed, just need to know where :)

**Comment by adamcrown** [comment]
Looks like they moved the repo to a new organization: http://apereo.github.io/cas/4.0.x/installation/Logout-Single-Signout.html. Their own website isn't even updated to point to it yet. I'll make a quick fix. Thanks for pointing this out.
