### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by timothychen01** [biola/rack-cas#65]
Code inside controller method:
`render :nothing => true, :status => :unauthorized`

Code inside `application.rb`:
`config.rack_cas.server_url = 'https://login.umd.edu/cas/login'  # UMD CAS System Integration`

Is there any way to get around this? Also doesn't work on Heroku when I try opening the app.

**Comment by adamcrown** [comment]
Most likely the SSL certificate your CAS server is using isn't trusted.

Try putting this is `config/application.rb`

```ruby
config.rack_cas.verify_ssl_cert = false
```

**Comment by timothychen01** [comment]
Hm...now I'm getting `RackCAS::ServiceValidationResponse::AuthenticationFailure`

**Comment by adamcrown** [comment]
Sorry I haven't gotten back to you about this for a while. Did you get it figured out? If you're still having trouble I'll need a bit more information about your environment and how it's setup. Thanks.

**Comment by adamcrown** [comment]
I'm going to close this due to inactivity. If anybody else has this issue just commend here and I'll reopen it.
