### ISSUE TITLE
After successful login (to MS AD) redirect back to application fails with SSL error

### ISSUE THREAD

**Issue by sviluppatore** [biola/rack-cas#76]
The title says much of what I can gather on the error. In my limited understanding, I am receiving an error from my application after the user has successfully logged into the CASino App with their active directory credentials. 

Here is the log output after I click a link that requires authentication. After I log in I am redirected back, but instead of the page I am expecting I end up seeing an error page telling me the certificate verify failed.

Any guidance would be appreciated. Thanks

> Started GET "/lazaretto/logs/new" for 127.0.0.1 at 2017-06-19 11:49:09 -0500
Processing by LogsController#new as HTML
  Rendered text template (0.0ms)
Filter chain halted as :authenticate! rendered or redirected
Completed 401 Unauthorized in 10ms (Views: 7.8ms | ActiveRecord: 0.0ms)
rack-cas: Intercepting 401 access denied response. Redirecting to CAS login.

> Started GET "/lazaretto/logs/new?ticket=ST-14978909498450-YQyTf3Exc2pFHMmgkI209iDRA1iFDuIKYdcA1Xg2" for 127.0.0.1 at 2017-06-19 11:49:09 -0500
rack-cas: Intercepting ticket validation request.
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed):
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:933:in `connect'
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
  rack-cas (0.9.2) lib/rack-cas/service_validation_response.rb:88:in `response'
  rack-cas (0.9.2) lib/rack-cas/service_validation_response.rb:98:in `xml'
  rack-cas (0.9.2) lib/rack-cas/service_validation_response.rb:62:in `success?'
  rack-cas (0.9.2) lib/rack-cas/service_validation_response.rb:15:in `user'
  rack-cas (0.9.2) lib/rack-cas/server.rb:24:in `validate_service'
  rack-cas (0.9.2) lib/rack/cas.rb:76:in `get_user'
  rack-cas (0.9.2) lib/rack/cas.rb:33:in `call'
  rack (1.6.8) lib/rack/etag.rb:24:in `call'
  rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.8) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  rack (1.6.8) lib/rack/handler/webrick.rb:88:in `service'
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /home/brent/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

  > Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.4ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (7.7ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.6ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (30.5ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (30.6ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /home/brent/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (55.3ms)

**Comment by sviluppatore** [comment]
i'm closing this; from what i can tell it has something to do with my dev environment; maybe some mismatched versions, but i am not totally sure on that.

**Comment by adamcrown** [comment]
@sviluppatore Sorry I didn't get to this sooner. Thanks for closing it up. It definitely looks like Ruby doesn't think your SSL cert is valid for some reason. Maybe it's self-generated?

**Comment by sviluppatore** [comment]
Yep it's on an app for internal use only. I ended up creating a new branch and I'm going to come back to it for a later update. Thank you for following up. Have a good day.Sent with SolMail App--------- Original Message ---------
From: Adam Crownoble 
To: biola/rack-cas 
Date: Sun Jun 25 07:51:39 CDT 2017
Subject: Re: [biola/rack-cas] After successful login (to MS AD) redirect back to application fails with SSL error (#76)

@sviluppatore Sorry I didn't get to this sooner. Thanks for closing it up. It definitely looks like Ruby doesn't think your SSL cert is valid for some reason. Maybe it's self-generated?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/biola/rack-cas","title":"biola/rack-cas","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/biola/rack-cas"}},"updates":{"snippets":[{"icon":"PERSON","message":"@adamcrown in #76: @sviluppatore Sorry I didn't get to this sooner. Thanks for closing it up. It definitely looks like Ruby doesn't think your SSL cert is valid for some reason. Maybe it's self-generated?"}],"action":{"name":"View Issue","url":"https://github.com/biola/rack-cas/issues/76#issuecomment-310900947"}}}
